### ISSUE TITLE
Serial port

### ISSUE THREAD

**Issue by direk** [eziosoft/MultiWii_EZ_GUI#24]
Cześć!

Zastanawiałeś się nad tym aby umożliwić w programie pobieranie danych z portu szeregowego emulowanego na USB, np /dev/ttyUSB0?

Po krótce dlaczego pytam - zastanawiam się nad zakupem radiomodemu który ma interfejs szeregowy. Taka linia umożliwia transmisję danych na dużo większe odległości niż marne 100m z BT, a modem taki podpięty do przejściówki RS232 -> USB, można podpiąć do kabelka USB OTG i na androidzie będziemy mieli wirtualny port :) 

Co nam to daje? Telemetrię z prawdziwego zdarzenia, bo zamiast tanich modemów można pociągnąć dane z dowolnego linku radiowego i ładnie wyświetlić na kolorowym ekranie smartfona :)

**Comment by eziosoft** [comment]
Cześć
Zastanawiałem sie ale jest za wiele "przeciw" niż "za"
-trudne w implementacji
-mało urządzeń obsługuje OTG
-z reguły wymaga roota
-małe zainteresowanie tematem

Jeżeli czujesz sie na siłach możesz dopisać taki kod.

**Comment by direk** [comment]
Cześć,

Powiem szczerze że w javie za mocny nie jestem, ale mogę spróbować. Sprawa
powinna być o tyle prosta że android od 3.0 w górę powinien mieć
wkompilowaną obsługę ft232, więc obejdzie się bez roota. Całość sprowadzała
by się do czytania z pliku :)

W dniu 10 marca 2013 22:54 użytkownik eziosoft
notifications@github.comnapisał:

> Cześć
> Zastanawiałem sie ale jest za wiele "przeciw" niż "za"
> -trudne w implementacji
> -mało urządzeń obsługuje OTG
> -z reguły wymaga roota
> -małe zainteresowanie tematem
> 
> Jeżeli czujesz sie na siłach możesz dopisać taki kod.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/eziosoft/MultiWii_EZ_GUI/issues/24#issuecomment-14690210
> .

## 

Pozdrawiam, Wojciech Kopyciak
http://www.direk.info | jid:kopyciak@gmail.com | +48 514 868 065 | +48 695
200 970

**Comment by eziosoft** [comment]
czesc
powinien miec wkompilowane ale jak ja testowalem to trzeba bylo zmieniac 
prawa do tego pliku aby go odczytac a to juz wymagalo roota.
tu masz troche info na ten temat:
https://code.google.com/p/android-serialport-api/wiki/android_to_rs232_guideline

Bartek

**Comment by eziosoft** [comment]
Dostalem ostatnio tablet z OTG. Jak tylko przyjdzie mi odpowiedni kabel to zaglebie sie w temat. Moze cos z tego wyjdzie.

**Comment by direk** [comment]
O, fajnie wiedzieć :)
Ja może też popróbuje - teraz czekam na kabelki OTG.

W dniu 15 marca 2013 08:09 użytkownik eziosoft
notifications@github.comnapisał:

> Dostalem ostatnio tablet z OTG. Jak tylko przyjdzie mi odpowiedni kabel to
> zaglebie sie w temat. Moze cos z tego wyjdzie.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/eziosoft/MultiWii_EZ_GUI/issues/24#issuecomment-14946419
> .

## 

Pozdrawiam, Wojciech Kopyciak
http://www.direk.info | jid:kopyciak@gmail.com | +48 514 868 065 | +48 695
200 970

**Comment by eziosoft** [comment]
i jak, próbowałeś cos ?

**Comment by eziosoft** [comment]
Zrobione!
