### ISSUE TITLE
Add support for Serial chips: FT232R, CDC/ACM (eg Arduino Uno) and possibly others

### ISSUE THREAD

**Issue by eziosoft** [eziosoft/MultiWii_EZ_GUI#27]

**Comment by stolken** [comment]
Bonjour Ezio,
Let me know if you want me to test it. Got an Galasy S3 (host mode) and a Arduino Leonardo based board. Also ordered an OTG cable.
A+

**Comment by eziosoft** [comment]
You can test it https://dl.dropboxusercontent.com/u/80566205/MultiWiiEZGUI1.apk
but it is still buggy and I don't know why. It works but it loses a lot of packets.

**Comment by eziosoft** [comment]
done
