### ISSUE TITLE
"dynamic refresh rate" and "avoid collision " for low speed half-duplex com-system

### ISSUE THREAD

**Issue by fryefryefrye** [eziosoft/MultiWii_EZ_GUI#43]
Send the command or request immediately after received a reply from copter.

**Comment by eziosoft** [comment]
Should be better when you choose "New request method" in config you can also reduce refresh time

**Comment by fryefryefrye** [comment]
Thank you.

I want to try to do something, but I do not have enough time to do that.

Regards.
在 2013-7-14 上午7:24，"eziosoft" notifications@github.com写道：
