### ISSUE TITLE
alt correction

### ISSUE THREAD

**Issue by eziosoft** [eziosoft/MultiWii_EZ_GUI#46]
However, when I go into config and tick the "alt correction" box ("alt set to zero when arming"). First the alt stays at zero, lift off -- two metres, three metres happy happy. Then I start to get horrid wrong values, 4500 metres, minus 196 metres. When I look at dashboard 1, the alt is all over the place. Other parameters seem sensible.

Without all correct, I have nice steady altitudes, even if they are offset with respect to the ground.

**Comment by SteveInBrussels** [comment]
Ezio, If I can help with this bug, let me know. steven(at)laycock.be

**Comment by eziosoft** [comment]
let me know if it is ok after update (Friday 07/06/2013)

**Comment by SteveInBrussels** [comment]
Salut Ezio

I did a mini test (too windy). You have fixed it. Behaved perfectly (but only flew to 5 metres). Zeroes on arming, stays zeroed for a few minutes (duration of test). “Un-zeroes” when disarmed. Zeroes happily again when re-armed.

MERCI and all the best, Steve

**Comment by SteveInBrussels** [comment]
Hi Ezio

I did a mini test (too windy). I pretty sure you have fixed it. Behaved perfectly (only flew to 5 metres). Zeros on arming, stays zeroed for a few minutes. “Unzeroes” when disarmed. Zeroes happily again when re-armed.

99% sure its fixed. 

THANKS and all the best,

Steve

**Comment by eziosoft** [comment]
corrected
