### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by robinson01** [eziosoft/MultiWii_EZ_GUI#59]
Hi!

I have crashed my quad with the blue-tooth running, probably the gui took control and gave full throttle. I haven't had any problem like this without bt. I use ZTE Grand X IN and MW 2.2.

**Comment by eziosoft** [comment]
Hi
I'm sorry about it. 
The only place where EZ_GUI can take a control over the quad is when you go to Advanced and Copter Control

also in MW 2.2 config.h file the line //#define RCSERIAL should be uncommented to allow control from GUI. If it wasn't uncommented you can't blame my software because there was no possibility to take over a control.
Could you please check this and let me know?

Thanks
Bart

**Comment by robinson01** [comment]
Hi!
Thank you for your reply. I think it is uncommented, because i can use gui
to control the quad. I will disable it, thank you!
2014.01.14. 18:05 ezt írta ("eziosoft" notifications@github.com):

**Comment by eziosoft** [comment]
remember that in 2.3 it is enable by default. By my app will never send commands to take a control over besides the Advanced->Copter Control Screen

Maybe it was other communication glitch.

**Comment by robinson01** [comment]
I use mw 2.2 and i haven't enabled it, but i am able to control the quad
through copter control screen. I haven't had any problem like this before,
neither after removing bt module.

2014.01.14. 18:51 ezt írta ("eziosoft" notifications@github.com):

**Comment by robinson01** [comment]
I have checked the RCSERIAL definition, it is commented out. How is that
possible, that I am still able to control the copter through the GUI?

2014/1/14 Zoltán Nagy znagy93@gmail.com

**Comment by eziosoft** [comment]
if you are using MultiWii before 2.3 and you have RCSERIAL commented out the control of the copter via MSP protocol should be not possible. If it is so there is a bug in MultiWii code.

In MultiWii 2.3 and later the possibility to control copter over MSP protocol is enabled by default and can't be turned off.
