### ISSUE TITLE
Altered values on PID page are not updated in flight controller

### ISSUE THREAD

**Issue by ProDrone** [eziosoft/MultiWii_EZ_GUI#63]
This issue started with MultiWii EZ-GUI 3.94.148 (also present in 3.95.149). Tested on both a Samsung S3 and a Sony tablet. It was working (PID adjustment) on both devices for my two quads for the past half year or so. Quad 1 uses MultiWii hardware with software v2.3; Quad 2 uses Naze32 with Baseflight. There is NO combination that can change the actual PID values. After i do a send to flight controller, the old values are still read back. This is very strange, since it needs to send and receive to do so... I am able to change other values on other pages, for instance minthrottle. All works fine when i link my PC via bluetooth using the chrome based baseflight configurator. So this excludes problems with both quads... Any suggestions ?

**Comment by eziosoft** [comment]
For safety reasons data are not send to multiwii when  Throttle Mid and Rc Rate  equals 0.

**Comment by ProDrone** [comment]
Thank you for your answer. Now it works. BUT you really should not do that. Leave safety and choice to the user. I have throttle-mid at 0 and throttle-expo at 0. This results in a linear throttle curve. Throttle-mid at 0 and any higher throttle expo results in a slowly progressive curve (not at all unsafe). rc-rate at zero may be dangerous, but what if i set it to 0.01 ? (still unsafe, no user control, but accepted by the system). If you decide to put this in an app, then at least notify the user at runtime when a save-to-eprom is attempted/rejected. now it looks like it is successfully done. A notice in the app update/change history would have saved me a lot of time... Baseflight configurator accepts these conditions and also has a separate receiver-tab for these items. Wrong PID values will probably cause more/quicker harm to a not-so-conscious (ab)user...

**Comment by eziosoft** [comment]
Here is why I added it.
Before MultiWii EZ-GUI 3.94.148 there was a serious bug in PID and from time to time values for RcRate RCExpo etc were set to 0. So I added this as a quick fix.
Now the main problem in PID is fixed so this restriction will be probably removed in next versions.
