### ISSUE TITLE
Log file date 01.01.70 00:59

### ISSUE THREAD

**Issue by rudi48** [eziosoft/MultiWii_EZ_GUI#66]
Hello EZIO,
Since 2014-12-30 the log file date written to the sdcard gets always the date 01.01.70 00:59,
if I transfer the file with "Android File Transfer" to the PC.
Before that date, it was OK.

Local on the Smartphone the file date seems to be OK.
So, I do not know where it comes from.
Regards, Rudolf

**Comment by eziosoft** [comment]
I have no idea what can cause this.
