### ISSUE TITLE
Mission Planner, Options, Distanze is too much

### ISSUE THREAD

**Issue by rudi48** [eziosoft/MultiWii_EZ_GUI#69]
Hello ezio,
Thank you for the good software.

In version 3.136.197 I have seen in Mission Planner, when you have loaded a mission, with a length of about 150 m, that the distance in window "Options" shows a value of about 11211778,00 m.
I think, that is too much.

As a feature it would be nice to show in the list of the waypoints, the distance from waypoint to the next waypoint, just below the coordinates.
Regards, Rudolf

**Comment by eziosoft** [comment]
corrected
