### ISSUE TITLE
Follow me incompatible with PROTOCOL_NAV

### ISSUE THREAD

**Issue by digitalentity** [eziosoft/MultiWii_EZ_GUI#70]
I figured that [this code](https://github.com/eziosoft/MultiWii_EZ_GUI/blob/c7f9014a9cbb149ed17298ab31aea1447567be40/src/com/ezio/multiwii/app/App.java#L593) should be made aware of protocol version. Otherwise FollowMe won't work when protocol is PROTOCOL_NAV

**Comment by marksev1** [comment]
Digitalentity you might want to report it also here http://ez-gui.com/report_issue/ so he maybe sees it earlier.

**Comment by eziosoft** [comment]
Actually I've change it a long time ago. I don't update this github repo. 
Right now follow me won't work for cleanflight at all. I will add it when you can confirm that PH  and altitude hold works more or less ok.
I plan to add more modes like: orbit me etc
I have few ideas but waiting for good altitude hold and PH.

**Comment by digitalentity** [comment]
@eziosoft 
Good to know that you have better waypoint support is the works! It will be good to have them supported when PH and AH code will be stable enough.
